### ISSUE TITLE
Doppler Radar

### ISSUE THREAD

**Issue by StratoSTARbyHIRO** [luesjo12/Weatherscan#2]
Unfortunately, the Doppler Radar isn't functioning as intended. It just shows an empty square (No basemaps, however there are radar overlays). 

I believe you need to reset your "OpenStreetMap" access token, so that it will work once again.

**Comment by JGriffin34432** [comment]
@DDroid Do you know where the API Key is, locate it so that you can go get your own and I need my own too.

**Comment by StratoSTARbyHIRO** [comment]
@JGriffin34432 you'll have to change the Mapbox URL on line 75 of "radar.js" in folder "js".  You can find out how to use your Mapbox access token here: https://www.mapbox.com/help/how-access-tokens-work/

Just use one of your styles from studio, make sure the share link is set to public.

**Comment by JGriffin34432** [comment]
@DDroid What style do I use?

**Comment by StratoSTARbyHIRO** [comment]
@JGriffin34432 Just create a basic style using a template (it should say to get started at the top on the "Studio" page)

**Comment by JGriffin34432** [comment]
So what URL to I replace with this one?

`https://api.mapbox.com/styles/v1/swaldner/cj8p1qym6976p2rqut8oo6vxr/tiles/{z}/{x}/{y}?access_token=pk.eyJ1Ijoic3dhbGRuZXIiLCJhIjoiY2o4ZGpjcnVvMHBhazMzcDVnanZmd2lobCJ9.Kr5329g4YyZIlnYfHNXRWA`

**Comment by StratoSTARbyHIRO** [comment]
@JGriffin34432 replace that link with on from your style in "Studio". Just press "Share & Use", then set it to "Public". Here's an important note: you need to keep `/tiles/{z}/{x}/{y}` in the URL, or add it as it may not work without it.... Just replace `swaldner/cj8p1qym6976p2rqut8oo6vxr` with the one from your shared style, and replace the access token with one from your account. If that doesn't work, change the same URL in the file named "radar_all_layers.js" in the same folder 

--Edit--
Also, if you're running this in Google Chrome, Mozilla or IE, don't forget to clear your browser cookies. This may help :)
